[package]
name = "spanr"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = { version = "1.0.19", features = ["span-locations"] }
html-escape = "0.2.6"
